# Etapa de build
FROM node:20-alpine AS builder
WORKDIR /app

# Copiamos package.json y lock
COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY apps ./apps
COPY core ./core

RUN npm install
RUN npm run build document-service

# Etapa de producción
FROM node:20-alpine AS production
WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist/apps/document-service ./dist

CMD ["node", "dist/main.js"]