version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: zero-trust
      POSTGRES_PASSWORD: 066512
      POSTGRES_DB: zerotrustdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  users:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    container_name: user-service
    ports:
      - "8001:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: zero-trust
      DB_NAME: zerotrustdb
      DB_PASSWORD: 066512
    depends_on:
      - db

  docs:
    build:
      context: .
      dockerfile: apps/document-service/Dockerfile
    container_name: doc-service
    ports:
      - "8005:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: zero-trust
      DB_NAME: zerotrustdb
      DB_PASSWORD: 066512
    depends_on:
      - db

  auth:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "8003:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: zero-trust
      DB_NAME: zerotrustdb
      DB_PASSWORD: 066512
    depends_on:
      - db

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    container_name: gateway
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: zero-trust
      DB_NAME: zerotrustdb
      DB_PASSWORD: 066512
    depends_on:
      - db

volumes:
  postgres_data: